# the code in this file is augmented by an ejs template
# and by loading the yaml into memory.
# some of these values will be replaced.
apiVersion: batch/v1
kind: Job
metadata:
  name: '{job_name}'
  labels:
    zmake-job: '{job_name}'
  finalizers:
    - foregroundDeletion
spec:
  template:
    metadata:
      labels:
        zmake-job: '{job_name}'
    spec:
      restartPolicy: Never
      containers:
        - name: job-executor
          image: '{pod_image}'
  backoffLimit: 0
