apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  labels:
    name: {pod_name}
spec:
  # important to set! otherwise will restart the pod.
  restartPolicy: Never
  containers:
    - name: {pod_name}
      image: {pod_image}
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
